---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robokube-meliazeng-github-io-v1-entity
  failurePolicy: Fail
  name: mentity.kb.io
  rules:
  - apiGroups:
    - robokube.meliazeng.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - entities
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robokube-meliazeng-github-io-v1-group
  failurePolicy: Fail
  name: mgroup.kb.io
  rules:
  - apiGroups:
    - robokube.meliazeng.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robokube-meliazeng-github-io-v1-model
  failurePolicy: Fail
  name: mmodel.kb.io
  rules:
  - apiGroups:
    - robokube.meliazeng.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - models
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robokube-meliazeng-github-io-v1-task
  failurePolicy: Fail
  name: mtask.kb.io
  rules:
  - apiGroups:
    - robokube.meliazeng.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tasks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robokube-meliazeng-github-io-v1-entity
  failurePolicy: Fail
  name: ventity.kb.io
  rules:
  - apiGroups:
    - robokube.meliazeng.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - entities
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robokube-meliazeng-github-io-v1-group
  failurePolicy: Fail
  name: vgroup.kb.io
  rules:
  - apiGroups:
    - robokube.meliazeng.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robokube-meliazeng-github-io-v1-model
  failurePolicy: Fail
  name: vmodel.kb.io
  rules:
  - apiGroups:
    - robokube.meliazeng.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - models
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-v1-pod
  failurePolicy: Fail
  name: vpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robokube-meliazeng-github-io-v1-task
  failurePolicy: Fail
  name: vtask.kb.io
  rules:
  - apiGroups:
    - robokube.meliazeng.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tasks
  sideEffects: None
