apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration   

webhooks:
- name: vpod.kb.io
  namespaceSelector:
    matchLabels:
      robokube.io: "true"