# permissions for end users to view tasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: robokube
    app.kubernetes.io/managed-by: kustomize
  name: task-viewer-role
rules:
- apiGroups:
  - robokube.meliazeng.github.io
  resources:
  - tasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - robokube.meliazeng.github.io
  resources:
  - tasks/status
  verbs:
  - get
