apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-tls
  namespace: default
spec:
  secretName: example-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  # The use of `selfsigned` is discouraged.
  # Instead, consider using an issuer based on the `ClusterIssuer` resource.
  # More information can be found here: https://cert-manager.io/docs/configuration/selfsigned/
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: example.com
  usages:
    - server auth
    - client auth
